import type { Metadata } from 'next'
import { LenisComponent } from '@/lib/lenis'
import { Inter } from 'next/font/google'
import '../styles/css/main.css'
import Navbar from '@/components/molecules/Navbar'
import Footer from '@/components/molecules/Footer'
import ReduxProvider from '@/components/ReduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="en">
      <body className={`${inter.className} layout`}>
        <ReduxProvider>
          <LenisComponent>
            <Navbar />
            {children}
            <Footer />
          </LenisComponent>
        </ReduxProvider>
      </body>
    </html>
  )
}
